import Head from "next/head";
import Header from "../components/Header";
import Main from "../components/Main";
import { useInsertData } from "../context/DataInsertProvider";
import InsertForm from "../components/InsertForm";
import { getSession } from "next-auth/react";

export default function Home() {
  const { isInsertForm } = useInsertData();
  return (
    <div>
      <Head>
        <title>Spotify demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" w-full relative">
        <Header />
        <Main />
        {isInsertForm ? <InsertForm /> : ""}
      </main>
    </div>
  );
}

export async function getServerSideProps({ req }) {
  const session = await getSession({ req });

  if (!session) {
    return {
      redirect: {
        destination: "/auth/signin",
        permanent: false,
      },
    };
  }

  return {
    props: { session },
  };
}
