import Head from "next/head";
import Header from "../components/Header";
import Main from "../components/Main";
import { BsGrid3X3GapFill } from "react-icons/bs";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Spotify demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" w-full">
        <Header />
        <Main />
      </main>
    </div>
  );
}
